### ISSUE TITLE
possible typo

### ISSUE THREAD

**Issue by tallforasmurf** [standardebooks/h-beam-piper_the-cosmic-computer#1]
In [this line](https://github.com/standardebooks/h-beam-piper_the-cosmic-computer/blob/master/src/epub/text/chapter-1.xhtml#L44)

> didn’t know what he was going to tell the people who would be waiting for him. No; he knew that; he just didn’t know how

To me, it should read "No; he knew *what*; he just didn't know *how*" with those italics. "he knew that" is grammatical but doesn't sound right. Can you check the scans?

**Comment by acabal** [comment]
The transcription is correct. You can find the page scans for our ebooks (if available) by opening the content.opf file and checking the `<dc:source>` element. In this case they're hosted at PG in a non-searchable format but it's better than nothing.
